In [17]:
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5])

print(arr_1d.shape)  #shape is the dimensions of the array
print(arr_1d.ndim)   #ndim is the number of dimensions of the array
print(arr_1d.size)   #size is the total number of elements in the array
print(arr_1d.dtype)  #dtype is the data type of the array elements
print(arr_1d.itemsize)  #itemsize is the size in bytes of each element in the array
print(arr_1d.nbytes)   #nbytes is the total size in bytes of the array
print(arr_1d.T)

(5,)
1
5
int64
8
40
[1 2 3 4 5]


In [16]:
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5,6])


print(arr_1d.mean()) ##mean is the average of the array elements
print(arr_1d.std())  ##std is the standard deviation of the array elements
print(arr_1d.sum()) ###sum is the sum of the array elements
print(arr_1d.min())  ###min is the minimum value of the array elements
print(arr_1d.max())  ###max is the maximum value of the array elements
print(arr_1d.argmin())  #argmin is the index of the minimum value of the array elements
print(arr_1d.argmax())  #argmax is the index of the maximum value of the array elements
print(arr_1d.reshape(2,3)) #reshape is used to change the shape of the array


3.5
1.707825127659933
21
1
6
0
5
[[1 2 3]
 [4 5 6]]


In [10]:
import numpy as np

arr_1d = np.array([1 ,2 ,3 ,4 ,5])

print(arr_1d)
print(arr_1d*2)
print(arr_1d+2)
print(arr_1d*arr_1d)
print(arr_1d**2)




[1 2 3 4 5]
[ 2  4  6  8 10]
[3 4 5 6 7]
[ 1  4  9 16 25]
[ 1  4  9 16 25]


In [1]:

import numpy as np

print("hello world")
print(np.__version__)

hello world
2.5.2


In [ ]:
import numpy as np

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print(arr_2d.shape)  #shape is the dimensions of the array
print(arr_2d.ndim)   #ndim is the number of dimensions of the array


zeros = np.zeros((2, 3))  # creates a 2x3 array of zeros
print(zeros)

eye = np.eye(3)  # creates a 3x3 identity matrix
print(eye)

arr = np.arange(2,20,4.1)  # creates an array of values from 2 to 20 with a step of 4.1
print(arr)

arr = np.linspace(0, 1, 5)  # creates an array of 5 values evenly spaced between 0 and 1
print(arr)

np.random.seed(0)  # sets the random seed for reproducibility
rand_arr = np.random.randn(2, 3)  # creates a 2x3 array of random values from a standard normal distribution
print(rand_arr)

In [34]:
data = np.random.randint(0, 10, size=(3, 4)) 

print(data)  # creates a 3x4 array of random integers between 0 and 10

mask = data > 5  # creates a boolean mask where elements greater than 5 are True
print(mask)

filtered_data = data[mask]  # filters the data using the boolean mask
print(filtered_data)  # prints the filtered data

[[1 4 9 8]
 [1 1 7 9]
 [9 3 6 7]]
[[False False  True  True]
 [False False  True  True]
 [ True False  True  True]]
[9 8 7 9 9 6 7]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
matrix_transpose = arr.T  # transposes the array
print(matrix_transpose)

matrix_auto = arr.reshape(2,-1)  # automatically reshapes the array to have 2 rows and as many columns as needed
print(matrix_auto)

flat = arr.ravel()  # flattens the array into a 1D array
print(flat)

v_stack = np.vstack((arr, arr))  # vertically stacks two arrays
print(v_stack)

h_stack = np.hstack((arr, arr))  # horizontally stacks two arrays
print(h_stack)

### Linear Algebra Operations

In [43]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

product = np.dot(arr1, arr2)  # performs matrix multiplication
print(product)

inv_arr = np.linalg.inv(arr1)  # computes the inverse of the array
print(inv_arr)

det = np.linalg.det(arr1)  # computes the determinant of the array
print(det)

eigenvalues, eigenvectors = np.linalg.eig(arr1)  # computes the eigenvalues and eigenvectors of the array
print(eigenvalues)
print(eigenvectors)

[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
[-0.37228132+0.j  5.37228132+0.j]
[[-0.82456484+0.j -0.41597356+0.j]
 [ 0.56576746+0.j -0.90937671+0.j]]
